import "./globals.css";
import type { Metadata } from "next";
import NavBar from "./components/Header";
import { Poppins } from "next/font/google";
import { ReduxProvider } from "./Provider/provider";

// Initialize the Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"], // Add multiple weights as needed
});

export const metadata: Metadata = {
  title: "Portfolio | Muhammad Ahmad",
  description: "Generated by Muhammad Ahmad",
  icons: "/ahmad.jpg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="antialiased flex flex-col items-center justify-center sm:pt-20 pt-20 px-2 sm:px-4 md:px-4">
        <ReduxProvider>
          <NavBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}