import "./globals.css";
import type { Metadata } from "next";
import NavBar from "./components/Header";
import { Montserrat } from "next/font/google";
import { ReduxProvider } from "./Provider/provider";

// Initialize the Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400"], // Add multiple weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="antialiased flex flex-col items-center justify-center pt-24">
        <ReduxProvider>
          <NavBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}