import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio | Muhammad Ahmad",
  description: "Generated by Muhammad Ahmad",
  icons: "/ahmad.jpg",
};

export default function ServerLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
